name: cs583
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - backcall=0.2.0
  - ca-certificates=2021.1.19
  - certifi=2020.12.5
  - decorator=4.4.2
  - ipython_genutils=0.2.0
  - jupyter_client=6.1.7
  - jupyter_core=4.7.1
  - ld_impl_linux-64=2.33.1
  - libedit=3.1.20191231
  - libffi=3.3
  - libgcc-ng=9.1.0
  - libsodium=1.0.18
  - libstdcxx-ng=9.1.0
  - ncurses=6.2
  - openssl=1.1.1j
  - parso=0.8.1
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=20.3.3
  - ptyprocess=0.7.0
  - python=3.8.5
  - python-dateutil=2.8.1
  - readline=8.1
  - setuptools=52.0.0
  - six=1.15.0
  - sqlite=3.33.0
  - tk=8.6.10
  - tornado=6.1
  - traitlets=5.0.5
  - wcwidth=0.2.5
  - wheel=0.36.2
  - xz=5.2.5
  - zeromq=4.3.3
  - zlib=1.2.11
  - pip:
    - absl-py==0.11.0
    - anyio==2.1.0
    - argon2-cffi==20.1.0
    - astunparse==1.6.3
    - async-generator==1.10
    - attrs==20.3.0
    - babel==2.9.0
    - bleach==3.2.3
    - cachetools==4.2.1
    - cffi==1.14.4
    - chardet==4.0.0
    - cycler==0.10.0
    - defusedxml==0.6.0
    - entrypoints==0.3
    - flatbuffers==1.12
    - gast==0.4.0
    - google-auth==1.24.0
    - google-auth-oauthlib==0.4.2
    - google-pasta==0.2.0
    - grpcio==1.34.1
    - h5py==3.1.0
    - idna==2.10
    - ipykernel==5.4.3
    - ipython==7.19.0
    - ipywidgets==7.6.3
    - jedi==0.18.0
    - jinja2==2.11.3
    - joblib==1.0.0
    - json5==0.9.5
    - jsonschema==3.2.0
    - jupyter-client==6.1.11
    - jupyter-packaging==0.7.12
    - jupyter-server==1.4.1
    - jupyterlab==3.0.9
    - jupyterlab-pygments==0.1.2
    - jupyterlab-server==2.3.0
    - jupyterlab-widgets==1.0.0
    - keras-preprocessing==1.1.2
    - kiwisolver==1.3.1
    - markdown==3.3.3
    - markupsafe==1.1.1
    - matplotlib==3.3.4
    - mistune==0.8.4
    - nbclassic==0.2.6
    - nbclient==0.5.1
    - nbconvert==6.0.7
    - nbformat==5.1.2
    - nest-asyncio==1.5.1
    - notebook==6.2.0
    - numpy==1.19.5
    - oauthlib==3.1.0
    - opt-einsum==3.3.0
    - packaging==20.9
    - pandas==1.2.2
    - pandocfilters==1.4.3
    - pillow==8.1.0
    - ply==3.11
    - prometheus-client==0.9.0
    - prompt-toolkit==3.0.14
    - protobuf==3.14.0
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycparser==2.20
    - pygments==2.7.4
    - pyparsing==2.4.7
    - pyrsistent==0.17.3
    - pytz==2021.1
    - pyzmq==22.0.2
    - requests==2.25.1
    - requests-oauthlib==1.3.0
    - rsa==4.7
    - scikit-learn==0.24.1
    - scipy==1.6.0
    - seaborn==0.11.1
    - send2trash==1.5.0
    - sniffio==1.2.0
    - tb-nightly==2.5.0a20210130
    - tensorboard-plugin-wit==1.8.0
    - termcolor==1.1.0
    - terminado==0.9.2
    - testpath==0.4.4
    - tf-estimator-nightly==2.5.0.dev2021013101
    - tf-nightly==2.5.0.dev20210130
    - threadpoolctl==2.1.0
    - typing-extensions==3.7.4.3
    - urllib3==1.26.3
    - webencodings==0.5.1
    - werkzeug==1.0.1
    - widgetsnbextension==3.5.1
